export const PEOPLE_FETCH_START = 'PEOPLE_FETCH_START';
export const PEOPLE_FETCH_FAIL = 'PEOPLE_FETCH_FAIL';
export const PEOPLE_RECEIVE = 'PEOPLE_RECEIVE';

export const PERSON_FETCH_START = 'PERSON_FETCH_START';
export const PERSON_FETCH_FAIL = 'PERSON_FETCH_FAIL';
export const PERSON_RECEIVE = 'PERSON_RECEIVE';

export const PLANET_FETCH_START = 'PLANET_FETCH_START';
export const PLANET_FETCH_FAIL = 'PLANET_FETCH_FAIL';
export const PLANET_RECEIVE = 'PLANET_RECEIVE';

export const SET_SORTING = 'SET_SORTING';
export const SET_FILTER = 'SET_FILTER';